# Configuration de la base de donnees Neon PostgreSQL
# Brasil Burger - Gestion des Ressources

# Type de base de donnees
db.type=postgresql

# Informations de connexion Neon
db.url=jdbc:postgresql://ep-raspy-glitter-a417bp77-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
db.username=neondb_owner
db.password=npg_vLxQ5bukUE3B
db.driver=org.postgresql.Driver

# Parametres de connexion
db.ssl=true
db.ssl.mode=require
